-- ~ Ejercicio 3: Obtener los nombres de los jugadores que han participado en los campeonatos 'C1' y 'C7'.

CREATE VIEW C1PLAYERS AS SELECT DISTINCT P# FROM PARTIDAS WHERE C# = 'C1';
CREATE VIEW C7PLAYERS AS SELECT DISTINCT P# FROM PARTIDAS WHERE C# = 'C7';

SELECT		DISTINCT NOMBRE
FROM		JUGADORES
WHERE		J# IN C1PLAYERS
AND			J# IN C7PLAYERS;
